spring.application.name=chronus-api
server.port=8081

cors.allowed-origins=http://localhost:3000

idclass.host=${IDCLASS_HOST:192.168.1.201}
idclass.port=${IDCLASS_PORT:443}
idclass.user=${IDCLASS_USER:admin}
idclass.password=${IDCLASS_PASSWORD:admin}