spring.devtools.restart.enabled=true

spring.datasource.url=jdbc:h2:mem:devdb
spring.jpa.show-sql=true

empresa.cnpj=${EMPRESA_CNPJ}
empresa.razaoSocial=${EMPRESA_RAZAO_SOCIAL}
empresa.cei=${EMPRESA_CEI:000000000000}
empresa.local=${EMPRESA_LOCAL}
empresa.numFabricacao=${EMPRESA_NUM_FABRICACAO:00000000000000000}